export default class FlutterunionadViewConfig {
  public static readonly adevent = "com.huazi.gtads_huawei/adevent";
  //SplashAdView
  public static readonly splashAdView = "com.huazi.gtads_huawei/SplashAdView"
  //BannerAdView
  public static readonly bannerAdView = "com.huazi.gtads_huawei/BannerAdView"
  //NativeAdView
  public static readonly nativeAdView = "com.huazi.gtads_huawei/NativeAdView"
  //DrawFeedAdView
  public static readonly drawFeedAdView = "com.huazi.gtads_huawei/DrawFeedAdView"
}